version: 1.0.{build}

image: Visual Studio 2022

before_build:
- dotnet restore src/MyParcelApi.Net.sln

build_script:
  - dotnet build src/MyParcelApi.Net.sln --configuration Release

#build:
#  project: src\MyParcelApi.Net.sln
#  verbosity: minimal

test: off  
#test:
#  assemblies:
#    - src\MyParcelApi.Tests\bin\Debug\MyParcelApi.Tests.dll

#after_test:
#- .\src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user "-filter:+[MyParcelApi*]*" -target:"vstest.console.exe" -targetargs:"/logger:Appveyor .\src\MyParcelApi.Tests\bin\Debug\MyParcelApi.Tests.dll" -output:".\coverage.xml"
#- .\src\packages\Codecov.1.0.5\tools\codecov -f "coverage.xml"