version: 1.0.{build}

image: Visual Studio 2022

before_build:
  - dotnet restore src/MyParcelApi.Net.sln

build_script:
  - dotnet build src/MyParcelApi.Net.sln --configuration Release

test_script:
  - ps: |
      $dll = "src\MyParcelApi.Tests\bin\Release\MyParcelApi.Tests.dll"
      & "C:\Tools\NUnit\nunit3-console.exe" $dll