version: 1.0.{build}

image: Visual Studio 2022

before_build:
  - dotnet restore src/MyParcelApi.Net.sln
  - nuget install NUnit.ConsoleRunner -Version 3.20.1 -OutputDirectory tools

build_script:
  - dotnet build src/MyParcelApi.Net.sln --configuration Release

test_script:
  - ps: |
      $runner = ".\tools\NUnit.ConsoleRunner.3.20.1\tools\nunit3-console.exe"
      $dll = "src\MyParcelApi.Tests\bin\Release\net48\MyParcelApi.Tests.dll"
      & $runner $dll